### ISSUE TITLE
What would the default hotmail and password be?

### ISSUE THREAD

**Issue by Rhomennik** [mgitgrullon/Eurodental#10]
![image](https://user-images.githubusercontent.com/24496303/45158423-f6a2eb00-b1b1-11e8-9b91-643c5a040f7f.png)
Help please :dancer:

**Comment by Rhomennik** [comment]
How can I access the database?

**Comment by mariogrullon-minted** [comment]
run rake db:seed to run the seed data, there's a user there in db/seeds.rb

**Comment by mariogrullon-minted** [comment]
The app is far from done btw, I created it for a specific client and currently it fills all their needs.

**Comment by Rhomennik** [comment]
Realmente me interesa mucho tu proyecto. Soy iniciante en ruby. pero quiero aportar con tu proyecto. voy a trabajar por el por que me interesa poder dejarlo mejor de lo que ya esta
