### ISSUE TITLE
Todo momento esta matando el rails S

### ISSUE THREAD

**Issue by Rhomennik** [mgitgrullon/Eurodental#11]
### cuando me logueo, o doy click en Clientes simplemeste el da un KILL### 
![image](https://user-images.githubusercontent.com/24496303/45161209-4afd9900-b1b9-11e8-96e6-625182dd7507.png)

**Comment by Rhomennik** [comment]
@mariogrullon 
Que sera que puede ser ?

**Comment by mariogrullon-minted** [comment]
no tengo idea, me funciona bien acá por eso no puedo hacerle debug, pero intenta lo siguiente, quita esta linea https://github.com/mgitgrullon/Eurodental/blob/master/Gemfile#L68 (para quitar la gema de puma_killer)y haz un `bundle install `

**Comment by Rhomennik** [comment]
No funciono, la quito y hago el `bundle install` pero da error al ejecutar `rails s`

Puede ser por la version del ruby?, actualmente esta en 

ruby 
> 2.3.1

y mi BUndle en 
> Bundler version 1.16.4

**Comment by mariogrullon-minted** [comment]
yo estoy usando ahora mismo la 2.3.3 y funciona, podrias intentar tambien con esa.

**Comment by Rhomennik** [comment]
Funciono.. Ahora ya esta Funcionando 100%, Muchas gracias

**Comment by Rhomennik** [comment]
Solo reinicie mi Servidor de OceanDigital.. Y ya no volvio a pasar

**Comment by Rhomennik** [comment]
Donde puedo encontrar el usuario y  la senha de esto
![image](https://user-images.githubusercontent.com/24496303/45166044-1e9b4a00-b1c4-11e8-814a-65421540a866.png)

**Comment by mariogrullon-minted** [comment]
esta hardcoded acá https://github.com/mgitgrullon/Eurodental/blob/master/app/controllers/admin_controller.rb#L16

**Comment by Rhomennik** [comment]
Gracias Mario!|
